version: '2'
services:
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - "3306:3306"
    volumes_from:
      - kitodo
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: kitodo
      MYSQL_USER: kitodo
      MYSQL_PASSWORD: kitodo

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kitodo:
    image: ubleipzig/kitodo-production:0.0.2
    container_name: kitodo
    links:
      - elasticsearch
    volumes:
      - /docker-entrypoint-initdb.d
    ports:
      - 8080:8080

volumes:
  esdata: