version: '2'
services:
  db:
    image: mysql:5.7
    volumes_from:
    - kitodo
    volumes:
    - db-data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "kitodo"
      MYSQL_USER: "kitodo"
      MYSQL_PASSWORD: "kitodo"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    environment:
      - "discovery.type=single-node"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kitodo:
    image: ubleipzig/kitodo-production:0.0.2
    volumes:
      - /docker-entrypoint-initdb.d
    environment:
      JAVA_OPTS: "-Xss10m"
    ports:
      - 8080:8080

volumes:
  es-data:
  db-data:
